#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/migrate.sh "message here"
# If no message is given, uses "auto".

MSG="${1:-auto}"

# Ensure we're in project root (directory of this script's parent)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

echo "==> Alembic autogenerate: ${MSG}"
alembic revision --autogenerate -m "${MSG}"

# Find the newest generated migration file (best-effort)
LATEST_FILE="$(ls -1t migrations/versions/*.py | head -n 1)"

echo "==> Generated: ${LATEST_FILE}"

# Detect "empty" migration (upgrade/downgrade both contain only 'pass' between autogen markers)
# This is a heuristic, but works well for the typical Alembic template.
if awk '
  /def upgrade\(\)/ {in_up=1}
  in_up && /# ### commands auto generated by Alembic/ {up_mark=1}
  up_mark && /# ### end Alembic commands/ {up_end=1; in_up=0}
  up_mark && !/pass|#|def upgrade|# ### commands auto generated by Alembic|# ### end Alembic commands/ && $0 ~ /[A-Za-z0-9_]/ {up_nonempty=1}

  /def downgrade\(\)/ {in_down=1}
  in_down && /# ### commands auto generated by Alembic/ {down_mark=1}
  down_mark && /# ### end Alembic commands/ {down_end=1; in_down=0}
  down_mark && !/pass|#|def downgrade|# ### commands auto generated by Alembic|# ### end Alembic commands/ && $0 ~ /[A-Za-z0-9_]/ {down_nonempty=1}

  END {
    # If we saw markers and found no real ops in both blocks -> empty
    if (up_mark && up_end && down_mark && down_end && !up_nonempty && !down_nonempty) exit 0;
    exit 1;
  }
' "${LATEST_FILE}"; then
  echo "==> No schema changes detected. Removing empty migration."
  rm -f "${LATEST_FILE}"
  exit 0
fi

echo "==> Applying migration: alembic upgrade head"
alembic upgrade head

echo "==> Done."